### ISSUE TITLE
Order state doesn't change to "complete" if the invoice is captured "online".

### ISSUE THREAD

**Issue by NikTob** [therouv/Magento-DebitPayment#60]
Hello,

if I create an invoice with "capture amount online" the order state doesn't switch to "complete".
If I capture offline it changed to "complete".

Is that a feature - or a bug? Because we use an extension which automatically generates invoices. And there you can online set "capture online" or "capture offline" generally - not for a special payment method. I also tested this issue after an uninstall of the extension - with the same result. 

An update would be nice :)
Thx!

**Comment by therouv** [comment]
That's a Magento thing. I recommend always to capture offline.
