### ISSUE TITLE
Issue with global BIC

### ISSUE THREAD

**Issue by C4rter** [therouv/Magento-DebitPayment#65]
Hi,

thanks for this extension, a real life saver for certain webshops.
But we've encountered an issue with global BICs.
Certain banks like "Postbank" are giving out a BIC like "PBNKDEFF".
https://www.postbank.de/privatkunden/pk_kontakt_brief.html

The last three digits, which are usually optional, are missing.
Unfortunately, the extension reports a wrong BIC because "PBNKDEFF" is missing the the database. Only "PBNKDEFF700" (and several other numbers) and "PBNKDEFFXXX" is available.

Can you provide a fix that validates these BICs as well? They are correct but are not matched because of the missing three optional digits.

Kind regards,
Benedikt Blank

**Comment by therouv** [comment]
Fixed with #68
