### ISSUE TITLE
Magento Upgrade and Module Upgrade to V1.9.1.0

### ISSUE THREAD

**Issue by thomasklosinsky** [therouv/Magento-DebitPayment#75]
Repost from Magento-Connect ;).

I just upgraded Magento from 1.7.0.2 to 1.9.1.0 and reinstalled your payment module.
Now, when trying to edit customers with orders with your payment method, I keep getting this error:

The requested Payment Method is not available.

Trace:
#0 /var/www/app/code/core/Mage/Payment/Model/Info.php(82): Mage::throwException('Die angefordert...')
#1 /var/www/app/code/core/Mage/Sales/Model/Quote/Payment.php(218): Mage_Payment_Model_Info->getMethodInstance()
#2 /var/www/app/code/community/Itabs/Debit/Model/Observer.php(170): Mage_Sales_Model_Quote_Payment->getMethodInstance()
#3 /var/www/app/code/community/Itabs/Debit/Model/Observer.php(125): Itabs_Debit_Model_Observer->_encryptPaymentData(Object(Mage_Sales_Model_Quote_Payment))
#4 /var/www/app/code/core/Mage/Core/Model/App.php(1338): Itabs_Debit_Model_Observer->encryptBankDataInAdminhtmlQuote(Object(Varien_Event_Observer))
#5 /var/www/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(Itabs_Debit_Model_Observer), 'encryptBankData...', Object(Varien_Event_Observer))
#6 /var/www/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('sales_quote_pay...', Array)
#7 /var/www/app/code/core/Mage/Core/Model/Abstract.php(391): Mage::dispatchEvent('sales_quote_pay...', Array)
#8 /var/www/app/code/core/Mage/Sales/Model/Quote/Payment.php(177): Mage_Core_Model_Abstract->_beforeSave()
#9 /var/www/app/code/core/Mage/Core/Model/Abstract.php(316): Mage_Sales_Model_Quote_Payment->_beforeSave()
#10 /var/www/app/code/core/Mage/Core/Model/Resource/Db/Collection/Abstract.php(652): Mage_Core_Model_Abstract->save()
#11 /var/www/app/code/core/Mage/Sales/Model/Quote.php(344): Mage_Core_Model_Resource_Db_Collection_Abstract->save()
#12 /var/www/app/code/core/Mage/Core/Model/Abstract.php(319): Mage_Sales_Model_Quote->_afterSave()
#13 /var/www/app/code/core/Mage/Sales/Model/Quote.php(1966): Mage_Core_Model_Abstract->save()
#14 /var/www/app/code/core/Mage/Sales/Model/Quote.php(1907): Mage_Sales_Model_Quote->save()
#15 /var/www/app/code/core/Mage/Sales/Model/Quote.php(363): Mage_Sales_Model_Quote->_afterLoad()
#16 /var/www/app/code/core/Mage/Adminhtml/Block/Customer/Edit/Tab/View/Accordion.php(54): Mage_Sales_Model_Quote->loadByCustomer(Object(Mage_Customer_Model_Customer))
#17 /var/www/app/code/core/Mage/Core/Block/Abstract.php(293): Mage_Adminhtml_Block_Customer_Edit_Tab_View_Accordion->_prepareLayout()
#18 /var/www/app/code/core/Mage/Core/Model/Layout.php(456): Mage_Core_Block_Abstract->setLayout(Object(Mage_Core_Model_Layout))
#19 /var/www/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('adminhtml/custo...', 'accordion')
#20 /var/www/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('adminhtml/custo...', 'accordion')
#21 /var/www/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#22 /var/www/app/code/core/Mage/Core/Model/Layout.php(206): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#23 /var/www/app/code/core/Mage/Core/Model/Layout.php(206): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#24 /var/www/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#25 /var/www/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#26 /var/www/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#27 /var/www/app/code/core/Mage/Adminhtml/Controller/Action.php(275): Mage_Core_Controller_Varien_Action->loadLayout(NULL, true, true)
#28 /var/www/app/code/core/Mage/Adminhtml/controllers/CustomerController.php(98): Mage_Adminhtml_Controller_Action->loadLayout()
#29 /var/www/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_CustomerController->editAction()
#30 /var/www/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('edit')
#31 /var/www/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#32 /var/www/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#33 /var/www/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#34 /var/www/index.php(186): Mage::run('', 'website')
#35 {main}

**Comment by gaiterjones** [comment]
I experienced this too and hacked a workaround, see my original post to see if you are experiencing the same bug.

**Comment by thomasklosinsky** [comment]
duplicate of #66
