### ISSUE TITLE
BIC Validation

### ISSUE THREAD

**Issue by sannc** [therouv/Magento-DebitPayment#79]
There is an obvious bug regarding the validation of BICs in the current version: Although ISO 9362 allows BICs with 11 OR 8 digits (see https://de.wikipedia.org/wiki/ISO_9362), only 11 digit codes are accepted.
 
Another bug is that, even though the BIC has not been required for German national transactions since Feb. 2014 (see https://de.wikipedia.org/wiki/ISO_9362), it still is required no matter what to get a set of account information validated.

**Comment by ingom** [comment]
How do I get 8 digit codes trough validation?
