### ISSUE TITLE
Fatal error: Class 'Itabs_Debit_Helper_Data' not found

### ISSUE THREAD

**Issue by sonsec** [therouv/Magento-DebitPayment#82]
Hello,

After installing the extension DebitPayment I cannot login to the admin area anymore, frontend is down and I got the following error: 

Fatal error: Class 'Itabs_Debit_Helper_Data' not found in /my/website/path/magento/app/Mage.php on line 547

The code in mage.php looks like this

    /**
     * Retrieve helper object
     *
     * @param string $name the helper name
     * @return Mage_Core_Helper_Abstract
     */
    public static function helper($name)
    {
        $registryKey = '_helper/' . $name;
        if (!self::registry($registryKey)) {
            $helperClass = self::getConfig()->getHelperClassName($name);
            self::register($registryKey, new $helperClass);
        }
        return self::registry($registryKey);
    }

Many thanks in advance for any support.

**Comment by sonsec** [comment]
I guess I cannot expect any answer anymore. I therefore deinstalled the extension and will refrain from using it. Not quite what I have expected in terms of support. :/

**Comment by therouv** [comment]
Hi @sonsec you need to clean the cache after installation. The problem itself is unfortunately not reproducible for me.
