### ISSUE TITLE
SUPEE-6788

### ISSUE THREAD

**Issue by gaiterjones** [therouv/Magento-DebitPayment#85]
Do you have an update for the changes required by the SUPEE-6788 Patch?

**Comment by therouv** [comment]
Hi @gaiterjones I released a new version 1.1.6 a couple of days ago where support for SUPEE-6788 is added: https://github.com/therouv/Magento-DebitPayment/releases/tag/1.1.6

**Comment by gaiterjones** [comment]
Thanks, I couldn't see any new commits on github thats why I asked.
