### ISSUE TITLE
Magento 1.9 internal server error after activation of DebitPayment

### ISSUE THREAD

**Issue by maschwa** [therouv/Magento-DebitPayment#86]
Hi folks,

i'am having a problem to get the module running and i hope somebody can help me. I tried to google etc. but had no real success. It's no permission problem etc. Everything ist fine before i activate the DebitPayment Module in ../modules/Itabs_Debit.xml

after i set <active>true</active> i get a nice 500 error message like this

<snippet>

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator to inform of the time the error occurred and of anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

</snippet>

Is it a compatibility problem with the version 1.9 (i have uses the newest version from github)? Does anybody has in idea where i can try to figure out the error?

Thanks for Feedback &
Greetings,
Marc

**Comment by therouv** [comment]
Hi @maschwa it's probably caused by [this setup script](https://github.com/therouv/Magento-DebitPayment/blob/master/src/app/code/community/Itabs/Debit/sql/debit_setup/mysql4-upgrade-1.0.7-1.0.8.php) which imports all bank data. It seems that you run into a timeout or that the memory limit is reached.

**Comment by maschwa** [comment]
thanks for the quick response. that was the reason. perfectly working after setting the timeout higher :-)
