### ISSUE TITLE
BIC-Prüfung nicht nach ISO 9362?

### ISSUE THREAD

**Issue by ssh-pw** [therouv/Magento-DebitPayment#96]
Hallo,

die BIC-Prüfung, die im OnePage-Checkout ausgeführt wird, verlangt zwingend die Angabe der Filiale- bzw. Abteilungs-Nummer (also die letzten drei Stellen der BIC). Diese Nummer ist aber optional (laut Spezifikation ISO 9362), d.h. z.B. bei der Berliner Volksbank ist die BIC BEVODEBB valide, wird aber von der Extension als falsch identifiziert. In der Datenbank ist die BIC BEVODEBBXXX hinterlegt, also nur mit der optionalen Abteilungs-Nummer.

Lässt sich dieses Problem lösen? Im Code gibt es anscheinend nur die direkte WHERE-Prüfung:
`$select = $adapter->select()->from($this->getMainTable(), 'bank_name')->where($field.'=?', $value);` in Itabs/Debit/Model/Resource/Bankdata.php ab Zeile 70.

Danke und viele Grüße
Patric

**Comment by therouv** [comment]
Hi @ssh-pw welche Version nutzt Du von dem DebitPayment Modul? 
Es ist bereits eine Variante implementiert, dass bei der Eingabe einer 8-stelligen BIC automatisch "XXX" mit angehängt wird, so dass die Validierung deshalb nicht fehlschlagen dürfte. Siehe https://github.com/therouv/Magento-DebitPayment/blob/develop/src/js/itabs/debit/blzcheck.js#L40

**Comment by ssh-pw** [comment]
Hallo @therouv , danke für das schnelle Feedback.

In der Tat war hier noch die Version 1.1.0 installiert. Der Magent Connect Downloader hatte keine Upates angezeigt. Bin jetzt manuell auf die 1.1.6 gegangen und siehe da, alles läuft :)

Vielen vielen Dank für die Info!

Grüße aus Berlin
Pat
