### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Arthey** [therouv/Magento-DebitPayment#97]
Hey,
since I installed the extension I get the following issues in error_logs of Apache:

mod_fcgid: read data timeout in 300 seconds
End of script output before headers: index.php

And the Shop is down.
I have tested the extension bei installing with the extension key (1.1.0) and with the 1.1.6 Version.
Same issue.

How can I solve this problem?

**Comment by therouv** [comment]
Hi @Arthey can you check if the solution of #86 works for you (setting the timeout higher)?

**Comment by Arthey** [comment]
Hey @therouv I have already set the timeout from 45 seconds to 300 seconds.
I have also changed the permissions. (Folders 755 / Files 644).

No Change.

**Comment by Arthey** [comment]
Problem solved.

The admin has set the following settings:

Apache:
FcgidBusyTimeout 500
FcgidIOTimeout 450

NGINX:
proxy_read_timeout 500;
